version: '3.8'

services:
  db:
    image: postgres:15
    container_name: foodservice_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: foodservice
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    container_name: foodservice_app
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/foodservice
    ports:
      - "8000:8000"

volumes:
  postgres_data:
